import { useGetAllProducts } from "../hooks/getAllProducts";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ProductCard } from "../components/ProductCard";
import { CreateProductForm } from "../components/CreateProductForm";
import { CreateProductButton } from "../components/CreateProductButton";

const Home: NextPage = () => {
  useGetAllProducts();
  return (
    <div className={styles.container}>
      <Head>
        <title>Product App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header
        style={{
          margin: "20px 20px 0 20px",
          padding: "0 0 20px 0",
          display: "flex",
          alignItems: "flex-start",
          justifyContent: "center",
          height: "100%",
        }}
      >
        <h1 className={styles.title} style={{ visibility: "hidden" }}>
          Products
        </h1>
      </header>
      <main>
        <CreateProductForm />
        <ProductCard
          id="1"
          title="title"
          description="This is a new product for people who work from home. It is made of cotton, and it is loose fitting. You will certainly be satisfied and comfortable waring these pants"
          productImgUrl="https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,w_730/at%2Fstyle%2F2020-03%2FWFH%20Pants%2FBrooklinen%20Jogger"
          priceInDollars={1.11}
        />
      </main>

      <footer>
        <CreateProductButton />
      </footer>
    </div>
  );
};

export default Home;
